### ISSUE TITLE
子应用刷新后找不到路由

### ISSUE THREAD

**Issue by sinlger** [issochen/qiankun-vue-demo#5]

**Comment by Adele0** [comment]
是不是线上环境刷新导致的？题主解决了吗？

**Comment by Adele0** [comment]
如果是F5刷新出现404 Not Found nginx/1.16.1, 需要配置Nginx
   参考：
    location /{
      root   /data/nginx/html;
      index  index.html index.htm;
      if (!-e $request_filename) {
        rewrite ^/(.*) /index.html last;
        break;
      }
    }

**Comment by sinlger** [comment]
好的
